services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
      - ./nginx/log:/var/log/nginx
    depends_on:
      gateway:
        condition: service_started
  gateway:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK
      - SERVER_USE_FORWARD_HEADERS=true
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul.${DOMAIN}
      - SPRING_CLOUD_CONSUL_PORT=443
      - SPRING_CLOUD_CONSUL_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=true
      - SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICE_NAME=apigateway
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=apigateway.microservices.${DOMAIN}
      - SPRING_CLOUD_CONSUL_DISCOVERY_PORT=443
      - SPRING_CLOUD_CONSUL_DISCOVERY_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_PATH=/management/health
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_INTERVAL=15s
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_TLS_SKIP_VERIFY=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.${DOMAIN}/realms/jhipster
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
  ms_route-mysql:
    image: mysql:9.2.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ms_route
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test:
        - CMD-SHELL
        - mysql -e "SHOW DATABASES;" && sleep 5
      interval: 5s
      timeout: 10s
      retries: 10
  ms_route:
    image: ms_route
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true

      - SPRING_CLOUD_CONSUL_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul.${DOMAIN}
      - SPRING_CLOUD_CONSUL_PORT=443
      - SPRING_CLOUD_CONSUL_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=true
      - SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_SERVICE_NAME=msroute
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS=msroute.microservices.${DOMAIN}
      - SPRING_CLOUD_CONSUL_DISCOVERY_PORT=443
      - SPRING_CLOUD_CONSUL_DISCOVERY_SCHEME=https
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_PATH=/management/health
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_INTERVAL=15s
      - SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_TLS_SKIP_VERIFY=true

      - SPRING_DATASOURCE_URL=jdbc:mysql://ms_route-mysql:3306/ms_route?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://ms_route-mysql:3306/ms_route?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://:${APP_F4_PASS}@${DOMAIN}:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.${DOMAIN}/realms/jhipster
      - SPRING_ELASTICSEARCH_URIS=http://${DOMAIN}:9200

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${DOMAIN}:9092
      - SPRING_KAFKA_SECURITY_PROTOCOL=SSL
      - SPRING_KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/app/config/kafka.truststore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=${APP_F4_PASS}
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION=/app/config/kafka.keystore.jks
      - SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD=${APP_F4_PASS}
      - SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD=${APP_F4_PASS}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8082/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    volumes:
      - ./kafka/ssl/kafka.truststore.jks:/app/config/kafka.truststore.jks
      - ./kafka/ssl/kafka.keystore.jks:/app/config/kafka.keystore.jks
    depends_on:
      ms_route-mysql:
        condition: service_healthy
